spring.application.name=WeatherApp
server.port=8095
weather.api.url=https://api.openweathermap.org/data/2.5
weather.api.key=ea46ee4cd5fdc9838921babcb9bd101d
resilience4j.circuitbreaker.instances.weatherService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.weatherService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.weatherService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.weatherService.waitDurationInOpenState=5s
spring.devtools.restart.enabled=false


